---
# tasks file for ansible-role-sublime-text

- include_tasks: install-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-Debian.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'
